### PR TITLE
Added embedded bash scripts, new firstinstall.sh file, other fixes

### PR DESCRIPTION
**Pull request by RobertofLocksley**
Hi, please review the commits I've been making to my fork throughout the day.

I've done a variety of changes and minor fixes here. I'm not entirely sure of your overall vision here, so I simply added what I could and tested where I could. Most of the changes I've made are in regards to making the code run inside the main .py file with subprocess.run, although you may find some other changes here and there. I've been testing the code on my pinephone and, where I found an issue, I changed it.

Please note that, aside from obtaining root privileges, the firstrun.sh file is somewhat redundant with the change to centralizing the code. Also note that one could do more with subprocess.run() here. I basically took the scripts that already existed and threw them into the code. Haven't had the chance to do more.

Also, an aside: I'm really not aware of the proper procedures with github and contributing as this is my first attempt of the kind. Only created a GH account yesterday lol.

Please let me know if there's anything else I can help with here.

All the best

### CODE REVIEW

**Comment by MadameMalady** [comment]
If you wanted to help with the registration code option some more, I made a discussions page on the main repository, it's basically a mini forum, and I have an  'idea' page open there that outlines what the option does so far, and what I'd like it to do, if you wanted, that would be something I could use help with

**Review by MadameMalady — APPROVED** [review]
I cloned your repository and tested everything, it seems to work quite well, merge approved once conflicts are resolved, I will look over that more later this evening

**Review by MadameMalady — APPROVED** [review]

**Comment by MadameMalady** [comment]
Having trouble figuring out what exactly is wrong with the files listed as conflicting, once that's resolved we'll merge it

**Comment by MadameMalady** [comment]
I don't know how to undo a merge approval, but there's a few things i'd like changed b4 merging;

The README.md file can be removed, I fixed the typo by hand, and it's complaining abt it conflictiong for some reason, the other issue is:
    
"This branch has conflicts that must be resolved
to resolve conflicts before continuing.
Conflicting files
My Waydroid Manager/My_Waydroid_Manager.py "

One of your changes was file locations or something, right?
can you temporarily revert that till post-merge, and we'll change it again after.

I also do not know github that well -_-" #8

**Review by MadameMalady — APPROVED** [review]

**Review by MadameMalady — APPROVED** [review]

**Comment by RobertofLocksley** [comment]
> I don't know how to undo a merge approval, but there's a few things i'd like changed b4 merging;
> 
> The README.md file can be removed, I fixed the typo by hand, and it's complaining abt it conflictiong for some reason, the other issue is:
> 
> "This branch has conflicts that must be resolved to resolve conflicts before continuing. Conflicting files My Waydroid Manager/My_Waydroid_Manager.py "
> 
> One of your changes was file locations or something, right? can you temporarily revert that till post-merge, and we'll change it again after.

Hey! Sorry I didn't see these over the weekend!

I have no idea why it listed any conflicts either. I looked over everything before I sent the merge request and I couldn't figure out why it was saying that either.
The only actual change I made that has file conflicts was rename the main "My Waydroid Manager" to "MyWaydroidManager"
Aside from that I only made changes to files that already existed (as well as set up the firstrun.sh)

**Comment by RobertofLocksley** [comment]
A question this time: is there anything in my codebase that isn't in yours anymore? I'm considering forking it again to maintain code parity. (Unless your aware of a better way. I'm no Github Guru)

**Comment by MadameMalady** [comment]
Yeah, it really hated that name change 4 some reason lol, hence the new branch

**Comment by MadameMalady** [comment]
I'm a bit tired today, but I plan to cleanup Unstable more soon and update main with a new version containing the version you worked on

**Comment by RobertofLocksley** [comment]
Amazing, thanks for the info. I'll put any future communications in the discussions tab :)

**Comment by RobertofLocksley** [comment]
>I had to delete the Readme (weird it let me, but yeah) to get it merged bc it kept whining at me.

Yeah, it must be that you have some control when you receive a pull request. I was so confused when I saw them missing this morning though XD

**Pull request merged**
